# Generated by Django 2.2.2 on 2019-11-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='images/')),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Showdata',
            fields=[
                ('bookno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('file', models.FilePathField()),
                ('price', models.FloatField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
